import type { CreateAiIntentDTO } from '../types'

export function getSystemIntents(hotelId: string): CreateAiIntentDTO[] {
  return [
    {
      hotelId,
      name: 'greeting',
      category: 'general',
      triggerPhrases: ['hola', 'buenos días', 'buenas tardes', 'buenas noches', 'hey', 'holi', 'buenas'],
      responseTemplate: '¡Hola {guestName}! Soy {botName}, recepcionista de {hotelName}. ¿En qué puedo ayudarte?',
      priority: 1,
      confidenceThreshold: 0.55,
    },
    {
      hotelId,
      name: 'booking_request',
      category: 'booking',
      triggerPhrases: ['reservar', 'quiero una habitación', 'quiero reservar', 'tienen disponibilidad', 'hay habitación', 'disponible', 'hacer una reserva', 'reservación'],
      responseTemplate: '¡Claro! Busquemos la habitación perfecta. ¿Qué fechas te interesan? Por ejemplo: "15 de julio al 18 de julio".',
      action: 'search_rooms',
      priority: 2,
      confidenceThreshold: 0.55,
    },
    {
      hotelId,
      name: 'checkin_info',
      category: 'faq',
      triggerPhrases: ['check in', 'check-in', 'checkin', 'hora de entrada', 'a qué hora se entra', 'hora de llegada', 'llegar antes'],
      responseTemplate: 'El check-in es a las {checkInTime}. Si llegás antes, podemos guardar tu equipaje sin problema. ¿Necesitás early check-in? Tiene un costo adicional.',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'checkout_info',
      category: 'faq',
      triggerPhrases: ['check out', 'check-out', 'checkout', 'hora de salida', 'hasta qué hora', 'salir más tarde', 'tarde checkout'],
      responseTemplate: 'El check-out es a las {checkOutTime}. ¿Te gustaría late checkout? Podés quedarte hasta más tarde por un cargo adicional.',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'wifi_info',
      category: 'faq',
      triggerPhrases: ['wifi', 'internet', 'clave wifi', 'contraseña wifi', 'red wifi', 'cómo conectarse'],
      responseTemplate: 'Red WiFi: {wifiNetwork} · Contraseña: {wifiPassword}. Es gratis en todo el hotel.',
      priority: 0,
      confidenceThreshold: 0.65,
    },
    {
      hotelId,
      name: 'parking_info',
      category: 'faq',
      triggerPhrases: ['parqueo', 'estacionamiento', 'parking', 'dónde aparcar', 'dónde estacionar', 'parqueadero'],
      responseTemplate: 'Tenemos estacionamiento gratuito para huéspedes. Está ubicado en la parte trasera del hotel.',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'breakfast_info',
      category: 'faq',
      triggerPhrases: ['desayuno', 'incluye desayuno', 'hora desayuno', 'dónde es el desayuno', 'comida incluida'],
      responseTemplate: 'El desayuno se sirve de 7:00 AM a 10:00 AM en el restaurante. ¿Te gustaría agregarlo a tu reserva? Cuesta $15 por persona.',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'pool_info',
      category: 'faq',
      triggerPhrases: ['piscina', 'alberca', 'horario piscina', 'piscina climatizada', 'piscina abierta'],
      responseTemplate: 'La piscina está abierta de 8:00 AM a 8:00 PM. Es de uso exclusivo para huéspedes.',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'transport_info',
      category: 'concierge',
      triggerPhrases: ['transporte', 'aeropuerto', 'traslado', 'taxi', 'cómo llegar', 'cómo llego', 'distancia aeropuerto'],
      responseTemplate: 'Ofrecemos traslado al aeropuerto por $40 USD. También podemos pedirte un taxi. ¿Querés reservar el traslado?',
      priority: 0,
      confidenceThreshold: 0.55,
    },
    {
      hotelId,
      name: 'payment_request',
      category: 'payment',
      triggerPhrases: ['pagar', 'cuánto debo', 'factura', 'invoice', 'pago', 'cuánto es', 'debo pagar', 'realizar pago'],
      responseTemplate: 'Déjame buscar tu reserva. ¿Me das tu número de confirmación o el email con el que reservaste?',
      action: 'send_payment_link',
      priority: 1,
      confidenceThreshold: 0.55,
    },
    {
      hotelId,
      name: 'modify_booking',
      category: 'booking',
      triggerPhrases: ['cambiar fecha', 'modificar reserva', 'cambiar reserva', 'extender estancia', 'mover reserva', 'cambiar habitación'],
      responseTemplate: 'Claro, déjame buscar tu reserva. ¿Me das tu número de confirmación o email?',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'cancel_booking',
      category: 'booking',
      triggerPhrases: ['cancelar', 'anular reserva', 'no voy a poder', 'cancelar reservación', 'cancelación', 'devolución'],
      responseTemplate: 'Entiendo. Déjame buscar tu reserva. ¿Número de confirmación o email? Tené en cuenta que aplican nuestras políticas de cancelación.',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'complaint_room',
      category: 'complaint',
      triggerPhrases: ['no funciona', 'roto', 'sucio', 'huele mal', 'problema', 'no sirve', 'descompuesto', 'anda mal'],
      responseTemplate: 'Lamento mucho el inconveniente. Déjame registrar el reporte para resolverlo cuanto antes. ¿Me decís el número de habitación y qué sucede exactamente?',
      action: 'register_incident',
      priority: 1,
      confidenceThreshold: 0.5,
    },
    {
      hotelId,
      name: 'housekeeping_request',
      category: 'service',
      triggerPhrases: ['limpieza', 'toallas', 'jabón', 'papel higiénico', 'sábanas', 'limpiar', 'aseo', 'shampoo', 'amenities'],
      responseTemplate: '¡Enseguida! Registro tu solicitud de {trigger}. ¿Número de habitación?',
      action: 'create_housekeeping_task',
      priority: 0,
      confidenceThreshold: 0.55,
    },
    {
      hotelId,
      name: 'maintenance_request',
      category: 'service',
      triggerPhrases: ['aire acondicionado', 'ac no', 'calefacción', 'ducha fría', 'agua caliente', 'no hay agua', 'luz no funciona', 'televisión no', 'tv no'],
      responseTemplate: 'Registrado. Voy a notificar al equipo de mantenimiento. ¿Número de habitación? Lo atenderán lo antes posible.',
      action: 'create_maintenance_ticket',
      priority: 0,
      confidenceThreshold: 0.5,
    },
    {
      hotelId,
      name: 'spa_request',
      category: 'service',
      triggerPhrases: ['spa', 'masaje', 'masajes', 'facial', 'relajación', 'tratamiento'],
      responseTemplate: '¡Excelente elección! Tenemos masajes relajantes ($50), terapéuticos ($65) y tratamientos faciales ($45). ¿Cuál te interesa?',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'restaurant_info',
      category: 'faq',
      triggerPhrases: ['restaurante', 'comida', 'cena', 'room service', 'menú', 'almuerzo', 'servicio a la habitación'],
      responseTemplate: 'El restaurante está abierto de 7 AM a 10 PM. También ofrecemos room service en ese horario. ¿Querés ver el menú?',
      priority: 0,
      confidenceThreshold: 0.6,
    },
    {
      hotelId,
      name: 'gratitude',
      category: 'general',
      triggerPhrases: ['gracias', 'perfecto', 'excelente', 'adiós', 'chao', 'hasta luego', 'nos vemos', 'bye'],
      responseTemplate: '¡Gracias a vos! ¿Cómo calificarías esta atención? Del 1⭐ al 5⭐. ¡Que tengas excelente día!',
      priority: -1,
      confidenceThreshold: 0.55,
    },
    {
      hotelId,
      name: 'human_agent',
      category: 'general',
      triggerPhrases: ['humano', 'persona real', 'recepcionista', 'gerente', 'hablar con alguien', 'con un humano', 'no robot'],
      responseTemplate: 'Claro, te transfiero con un agente ahora mismo. Un momento por favor.',
      action: 'escalate_to_human',
      priority: 5,
      confidenceThreshold: 0.5,
    },
    {
      hotelId,
      name: 'emergency',
      category: 'emergency',
      triggerPhrases: ['emergencia', 'doctor', 'ambulancia', 'policía', 'incendio', 'médico', 'hospital', 'accidente'],
      responseTemplate: '¡Emergencia detectada! No te muevas, te estamos contactando YA.',
      action: 'escalate_to_human',
      priority: 10,
      confidenceThreshold: 0.4,
    },
  ]
}
